# Generated by Django 3.0.3 on 2020-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapps', '0002_auto_20200326_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=18)),
            ],
        ),
    ]
